### PR TITLE
Improve Flood-fill algorithm

### PR DESCRIPTION
**Pull request by naveensingh**
This PR addresses various issues with existing Flood fill implementation

### Changes:
 - Switch to vector/path-based flood filling instead of directly using bitmaps:
      - Allows use of a low tolerance flood filling so that lighter shades of colors aren't ignored
      - Avoids leaving that 1px boundary around the filled area using an appropriate stroke width
      - Allows saving flood-fill ops to SVG files, we couldn't do this with bitmap-based flood filling
 - Optimized algorithm, it's 20% faster compared to the previous releases.
 - Save drawing state to a state holder object to avoid throwing `TransactionTooLargeException` when there are a large number of operations.

### Preview:

<details>

<summary>Click to expand!</summary>

https://user-images.githubusercontent.com/36371707/224423398-15082881-06a6-48a3-9b05-1bb1b860602e.mp4

_Slow-mo:_

https://user-images.githubusercontent.com/36371707/224423406-f7d033d8-f3c6-4138-af8c-1be79769ea8b.mp4

</details>

### CODE REVIEW

**Comment by tibbi** [comment]
lets see how it works, thanks :) But if I draw a circle with some very light color and use flood fill, it still leaves the circle itself and colors the whole screen

**Comment by Naveen3Singh** [comment]
just tested, we can reduce the tolerance to 1 to allow very light shades (e.g. #020202 on #000000). Since the stroke width is set to 5, it doesn't leave any unfilled boundary.

**Comment by tibbi** [comment]
you can try. This specific issue is about light colors, not widths

**Comment by Naveen3Singh** [comment]
oh, I meant the stroke width **now** used by flood fill (it uses vector paths now just like hand-drawn shapes).

https://github.com/SimpleMobileTools/Simple-Draw/pull/272 does it.

**Pull request merged**
