### PR TITLE
Dutch

### PR DESCRIPTION
**Pull request by ltGuillaume**
Note: "Afterall" is not a proper English word.

### CODE REVIEW

**Comment by tibbi** [comment]
added Pro to the app title but removed a space, it is too long (51 chars)

**Comment by ltGuillaume** [comment]
Ah, yes, that's another way of handling it 👍 

> Note: "Afterall" is not a proper English word.

Saw this??

**Comment by tibbi** [comment]
ye, but it looks proper-ish enough for me

**Comment by ltGuillaume** [comment]
https://en.wiktionary.org/wiki/afterall

**Comment by tibbi** [comment]
well I dont really feel like changing every string, you can do it if you are bored :)

**Comment by ltGuillaume** [comment]
Hehe, no chance ;-)

**Comment by tibbi** [comment]
I do actually, will do it

**Pull request merged**
