### PR TITLE
Zoom towards the center of the screen

### PR DESCRIPTION
**Pull request by CactiChameleon9**
See #242 for previous details:
> This helps fix https://github.com/SimpleMobileTools/Simple-Draw/issues/138 and https://github.com/SimpleMobileTools/Simple-Draw/issues/166.
>
> The old zoom behaviour means that when you zoom in after moving the canvas, you end up zooming away from what you were recently drawing. In other words, the center of the zoom was at (0, 0) or the original center of the image.
>
>This PR fixes that by adjusting the canvas position based of how much is zoomed so that the zoom is focused towards the center of what you can see (the screen) - fixing any weirdness with the zoom that was after moving.

### CODE REVIEW

**Comment by tibbi** [comment]
I dont really see what this changes, can you do some videos about it or a better explanation?

**Comment by CactiChameleon9** [comment]
OK, so do the following (on normal SimpleDraw):
- Open the app
- Draw a circle
- Zoom in and out (for comparison)
- Move the canvas **a lot** in any direction
- Draw a triangle
- Try zooming in/out

You will notice that when zooming, the triangle moves sideways a lot - moving away from whats on screen.

This is because the zoom is zooming towards the centre of the canvas (where we drew our circle)

This PR fixes that by changing the zoom behaviour so that we zoom towards what is in the centre of the screen, not the centre when we first opened the app.

**Comment by CactiChameleon9** [comment]
(I can get a video too you - but I don't think its that clear what I mean)

**Comment by tibbi** [comment]
try merging with the latest master if it wasnt the related gesture glitch only

**Comment by CactiChameleon9** [comment]
What do you mean by "try merging with the latest master". What I have just done? ("Merge branch 'SimpleMobileTools:master' into patch-1") 

That just made an extra commit for no reason

**Comment by tibbi** [comment]
ok, I see. The PR improves the situation, but it still isnt perfect. We should zoom to the center between 2 fingers, not the center of the screen. Thanks though

**Comment by CactiChameleon9** [comment]
> ok, I see. The PR improves the situation, but it still isnt perfect. We should zoom to the center between 2 fingers, not the center of the screen. Thanks though

Yeah - it isn't perfect - but it is a massive improvement when taking notes that span a lot of area!

Thanks for merging :tada:

**Pull request merged**
