### PR TITLE
Allow opening existing .svg files

### PR DESCRIPTION
**Pull request by XyLoNaMiyX**
Hey :)

I've been implementing the loading logic for `.svg` files. It actually uses an XML parser for the parsing part, although the SVG path data (for example, `<path d="M24,52 …`) is my own implementation, thus it will result in undefined behaviour if the `.svg` trying to be loaded was *not* exported with Simple Draw.

Currently, it parses the `.svg` files and already loads the canvas. Only missing the "Load" part on the menu. How should a Simple application implement the "Open file" dialog?

### CODE REVIEW

**Comment by XyLoNaMiyX** [comment]
By the way, this closes #13, kind of, unless you want the users to be able to load *all* kind of images (`.png`, `.bmp` and such) and use them as a background to paint on.

**Comment by tibbi** [comment]
Hey, nice. Well Simple Draw is quite outdated as it doesnt even contain the Commons library yet. Ill get to rewriting it to the shared codebase and kotlin soon. Quite a lot of things are needed for the filepicker and storage permissions, so it doesnt really make much sense to have a glued filepicker now. Id wait with the dialog till the rewrite.

**Comment by XyLoNaMiyX** [comment]
Alright, keep me updated! What are we doing with this pull request in the meantime then?

**Comment by tibbi** [comment]
well I can accept it, will test it properly once Im rewriting. Hope it works :)

**Comment by XyLoNaMiyX** [comment]
> Hope it works :)

I hope so too, I couldn't properly test loading all kind of images (like, different backgrounds and colours and such) because there's no "Load" button so I did a quick workaround :P

**Comment by tibbi** [comment]
Ive rewritten Simple Draw in kotlin with an Open file menu item, seems to be working quite nice. Tested only svgs created by simple draw so far, not other ones.

**Comment by Lonami** [comment]
That's cool! Thanks for the update @tibbi ;)

Did loading with different background colors work?

**Comment by tibbi** [comment]
yea, different background colors with too

**Pull request merged**
