### PR TITLE
Add ability to rotate the canvas (closes #32)

### LINKED ISSUE #32: Rotation option
Please, add an ability to rotate the image;

Or, in alternative, change the position of the color box (for example on the bar)

### PR DESCRIPTION
**Pull request by XyLoNaMiyX**

### CODE REVIEW

**Comment by XyLoNaMiyX** [comment]
Bump @tibbi. If you don't have time to build this yourself I can also provide an `.apk`? 😋

**Comment by tibbi** [comment]
ill check it today already

**Comment by tibbi** [comment]
or tomorrow, trying to release the new gallery asap

**Comment by XyLoNaMiyX** [comment]
Haha no worries, I know you're actively working on all these projects.

**Comment by tibbi** [comment]
loos ok, releasing a new version with it. Thanks!

**Comment by XyLoNaMiyX** [comment]
Please keep in mind the little issue (Dialog window leakes) when the user tries to save an image but the screen rotates.

**Comment by tibbi** [comment]
theres probably a lot of leaking and other issues related to rotating all around my apps, i just dont care about it for now.

**Pull request merged**
