### PR TITLE
Allow saving to svg

### PR DESCRIPTION
**Pull request by XyLoNaMiyX**

### CODE REVIEW

**Comment by XyLoNaMiyX** [comment]
Now we need to show a selector on the save dialog to choose either `.png` or `.svg`, but this already addresses #19 and exporting seems to work just fine on the tests I've done.

**Comment by XyLoNaMiyX** [comment]
If you ever consider storing the alpha value `.svg` in order to add this to my implementation you would need to get the alpha channel separately and convert it from `0..255 → 0..1` to set `stroke-opacity="float"`.

**Comment by tibbi** [comment]
looks great, just make the png or svg picker a radiobutton, like the copy/move dialog in the gallery. Ill tweak some code style things then
screenshot_20170119-225158

**Comment by XyLoNaMiyX** [comment]
> just make the png or svg picker a radiobutton

You think this will work fine if then we decide to add even more formats, like `.bmp`? Won't it take too much space?

**Comment by tibbi** [comment]
its fine, I want consistency between apps

**Comment by XyLoNaMiyX** [comment]
[`d3a672f`](https://github.com/SimpleMobileTools/Simple-Draw/pull/42/commits/d3a672f2482a27e29511a5e792f8c20d248e3fd2)

new look

**Comment by tibbi** [comment]
hey o/
looks nice, thanks!

**Pull request merged**
