### PR TITLE
Added clear color (implements and closes #6)

### LINKED ISSUE #6: Allow changing the background color

### PR DESCRIPTION
**Pull request by XyLoNaMiyX**

### CODE REVIEW

**Comment by tibbi** [comment]
hah nice, but it needs some tweaks. I would leave Clear as it is, simply clearing the drawings.
Another actionbar button would change the background color, without affecting the drawings on it, thats how I would like it to be as a user. Here is some stackoverflow answer about it http://stackoverflow.com/questions/10268724/android-change-canvas-background-color-without-losing-any-drawings-from-it . I havent tested it, but we need something like that.

**Comment by XyLoNaMiyX** [comment]
> (StackOveflow) Android change canvas background color without losing any drawings from it

Since you actually draw every single path `onDraw`, we can simply `invalidate()` the canvas, clear the new color, and draw the old paths on top. Drawings would not be affected.

> I would leave Clear as it is, simply clearing the drawings.

I see your point, you want to be able to change the background without affecting the drawings (rather than clearing a color).

> Another actionbar button would change the background color

I didn't want, however, add too many options to the menu since this is a _Simple_ app. That's why I set it on clear.

**Comment by tibbi** [comment]
well we simply need more items in the actionbar, Clear and changing the background color are 2 totally separate features, they shouldn't be merged in one.

**Comment by XyLoNaMiyX** [comment]
It's great that we can actually use the `Canvas.getBackground` property without the need of further additions.

**Comment by XyLoNaMiyX** [comment]
→ **Note** that the values used to determine whether the white or black arrow should be used are found [here](http://alienryderflex.com/hsp.html). There are two commits because I used the old ones (oops!).

**Comment by tibbi** [comment]
yeah nice, good job!
Ive just added the new string to the other language files too and corrected some formatting

**Comment by XyLoNaMiyX** [comment]
Alright thanks for merging!

**Pull request merged**
